var data = {
  "Art": {
    "art": "<h3>art</h3><p>art is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p><h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p><h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p>",
    "Algebra2": "<h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p><h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p><h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p>",
    "Algebra3": "<h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p><h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p><h3>Algebra</h3><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols.</p>",
    "Geometry": "<h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p><h3>Geometry</h3><p>Geometry is the branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.</p>"
  },
  "Science": {
    "Physics": "<h3>Physics</h3><p>Physics is the natural science that studies matter, its motion, and behavior through space and time.</p>",
    "Chemistry": "<h3>Chemistry</h3><p>Chemistry is the scientific study of the properties and behavior of matter.</p>"
  },
  "History": {
    "Ancient": "<h3>Ancient History</h3><p>Ancient history is the study of the written past from the beginning of recorded human history.</p>",
    "Modern": "<h3>Modern History</h3><p>Modern history is the history of the modern era, post-Medieval times.</p>"
  }
};

generateSidebar();